org: richik
app: webhooks-qb
service: qb-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  versionFunctions: false
  stage: v1
  region: ap-south-1
  apiName: ${self:service}
  memorySize: 256
  logRetentionInDays: 14

functions:
  api:
    handler: handler.handler
    timeout: 300
    events:
      - httpApi: '*'

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-offline
